In [1]:
import pandas as pd
import numpy as np
import os, sys
import math
import copy

## PROCESS FIRST SAMPLE

In [2]:
input = ["O....#....",
"O.OO#....#",
".....##...",
"OO.#O....O",
".O.....O#.",
"O.#..O.#.#",
"..O..#O..O",
".......O..",
"#....###..",
"#OO..#...."]

In [4]:
mapping = {'O':1, '.':0, '#':2}
panel = []
for line in input:
    row = [mapping[x] for x in line]
    panel.append(row)
np_panel = np.array(panel)
np_panel

array([[1, 0, 0, 0, 0, 2, 0, 0, 0, 0],
       [1, 0, 1, 1, 2, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0, 2, 2, 0, 0, 0],
       [1, 1, 0, 2, 1, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 1, 2, 0],
       [1, 0, 2, 0, 0, 1, 0, 2, 0, 2],
       [0, 0, 1, 0, 0, 2, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [2, 0, 0, 0, 0, 2, 2, 2, 0, 0],
       [2, 1, 1, 0, 0, 2, 0, 0, 0, 0]])

In [55]:
def move_up(panel):
    num_rows, num_cols  = panel.shape
    for col in range(num_cols):
        row = 0
        next_row = 0
        while row < num_rows - 1:
            #print(f'Checking space in row {row} col {col}')
            if panel[row,col] == 0:
                next_row = max(next_row, row + 1)
                while panel[next_row, col] == 0 and next_row < num_rows - 1:
                    next_row += 1
                if panel[next_row,col] == 2: # FOUND FIXED ROCK, RESUME FROM THE POSITION AFTER THAT AND NO ROCK FALLS
                    row = next_row + 1
                if panel[next_row,col] == 0: # REACHED THE END IN A WHITE SPACE, JUMP TO THE END
                    row = next_row + 1
                if panel[next_row,col] == 1: # FOUND FALLING ROCK, IT FALLS AND WE MOVE UP 1
                    panel[row,col] = 1
                    panel[next_row,col] = 0
                    row += 1
            else:
                row += 1
    return panel

def compute_weight(panel):
    num_rows, num_cols = panel.shape
    weight = 0
    for row in range(num_rows):
        row_weight = np.sum(panel[row,:] == 1)*(num_rows-row)
        #print(f'Checking row {row} with unit weight {num_rows - row}: {row_weight}')
        weight += row_weight
    return weight


In [38]:
np_panel_shift = np_panel.copy()
np_panel_shift = move_up(np_panel_shift)
print(compute_weight(np_panel_shift))
np_panel_shift

Checking row 0 with unit weight 100
Checking row 1 with unit weight 99
Checking row 2 with unit weight 98
Checking row 3 with unit weight 97
Checking row 4 with unit weight 96
Checking row 5 with unit weight 95
Checking row 6 with unit weight 94
Checking row 7 with unit weight 93
Checking row 8 with unit weight 92
Checking row 9 with unit weight 91
Checking row 10 with unit weight 90
Checking row 11 with unit weight 89
Checking row 12 with unit weight 88
Checking row 13 with unit weight 87
Checking row 14 with unit weight 86
Checking row 15 with unit weight 85
Checking row 16 with unit weight 84
Checking row 17 with unit weight 83
Checking row 18 with unit weight 82
Checking row 19 with unit weight 81
Checking row 20 with unit weight 80
Checking row 21 with unit weight 79
Checking row 22 with unit weight 78
Checking row 23 with unit weight 77
Checking row 24 with unit weight 76
Checking row 25 with unit weight 75
Checking row 26 with unit weight 74
Checking row 27 with unit weight 73
C

array([[1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 0, 1],
       [0, 1, 1, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 2],
       [0, 0, 0, ..., 2, 2, 2],
       [0, 0, 0, ..., 1, 0, 0]])

## PROCESS PART 1

In [39]:
# READ FILE
inputfilepath = './input.txt'

input = []
with open(inputfilepath,'r') as f:
    for line in f:
        input.append(line.rstrip())

In [44]:
mapping = {'O':1, '.':0, '#':2}
panel = []
for line in input:
    row = [mapping[x] for x in line]
    panel.append(row)
np_panel = np.array(panel)
print(np_panel.shape)
np_panel

(100, 100)


array([[1, 0, 0, ..., 0, 0, 1],
       [0, 1, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 2],
       [0, 0, 0, ..., 2, 2, 2],
       [1, 0, 0, ..., 1, 0, 0]])

In [49]:
np_panel_shift = np_panel.copy()
np_panel_shift = move_up(np_panel_shift)
print(compute_weight(np_panel_shift))
np_panel_shift

Checking row 0 with unit weight 100: 6000
Checking row 1 with unit weight 99: 4356
Checking row 2 with unit weight 98: 3234
Checking row 3 with unit weight 97: 2425
Checking row 4 with unit weight 96: 1824
Checking row 5 with unit weight 95: 1330
Checking row 6 with unit weight 94: 1786
Checking row 7 with unit weight 93: 1488
Checking row 8 with unit weight 92: 2116
Checking row 9 with unit weight 91: 1820
Checking row 10 with unit weight 90: 1800
Checking row 11 with unit weight 89: 1780
Checking row 12 with unit weight 88: 1760
Checking row 13 with unit weight 87: 1566
Checking row 14 with unit weight 86: 1634
Checking row 15 with unit weight 85: 1700
Checking row 16 with unit weight 84: 2184
Checking row 17 with unit weight 83: 1660
Checking row 18 with unit weight 82: 2296
Checking row 19 with unit weight 81: 2349
Checking row 20 with unit weight 80: 2000
Checking row 21 with unit weight 79: 2054
Checking row 22 with unit weight 78: 1950
Checking row 23 with unit weight 77: 1925
C

array([[1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 0, 1],
       [0, 1, 1, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 2],
       [0, 0, 0, ..., 2, 2, 2],
       [0, 0, 0, ..., 1, 0, 0]])

## PROCESS SECOND SAMPLE

In [50]:
input = ["O....#....",
"O.OO#....#",
".....##...",
"OO.#O....O",
".O.....O#.",
"O.#..O.#.#",
"..O..#O..O",
".......O..",
"#....###..",
"#OO..#...."]

In [52]:
mapping = {'O':1, '.':0, '#':2}
panel = []
for line in input:
    row = [mapping[x] for x in line]
    panel.append(row)
np_panel = np.array(panel)
print(np_panel.shape)
np_panel

(10, 10)


array([[1, 0, 0, 0, 0, 2, 0, 0, 0, 0],
       [1, 0, 1, 1, 2, 0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0, 2, 2, 0, 0, 0],
       [1, 1, 0, 2, 1, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 1, 2, 0],
       [1, 0, 2, 0, 0, 1, 0, 2, 0, 2],
       [0, 0, 1, 0, 0, 2, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [2, 0, 0, 0, 0, 2, 2, 2, 0, 0],
       [2, 1, 1, 0, 0, 2, 0, 0, 0, 0]])

In [53]:
#NORTH, WEST, SOUTH, EAST
def cycle(panel):
    # NORTH
    panel = move_up(panel)
    # WEST
    panel = np.rot90(panel,k=-1)
    panel = move_up(panel)
    # SOUTH 
    panel = np.rot90(panel,k=-1)
    panel = move_up(panel)
    # EAST
    panel = np.rot90(panel,k=-1)
    panel = move_up(panel)
    # ROTATE BACK NORTH
    panel = np.rot90(panel,k=-1)

    return panel


In [69]:
np_panel_copy = np_panel.copy()
positions_visited = {}

for i in range(1,1_000_00):

    np_panel_copy = cycle(np_panel_copy)

    rock_idx = np.where(np_panel_copy == 1)
    rock_idx_tuple = tuple(zip(rock_idx[0], rock_idx[1]))

    if rock_idx_tuple in positions_visited.keys():        
        cycle_lenght = i - positions_visited[rock_idx_tuple][0]
        print(f'Found cycle at iteration {i} of lenght {cycle_lenght}')
        break
    else:
        positions_visited[rock_idx_tuple] = (i, compute_weight(np_panel_copy))

    if i % 1000 == 0:
        print(f'Completed {i} cycles')

print(compute_weight(np_panel_copy))
print(np_panel_copy)

Found cycle at iteration 10 of lenght 7
69
[[0 0 0 0 0 2 0 0 0 0]
 [0 0 0 0 2 0 0 0 1 2]
 [0 0 0 0 0 2 2 0 0 0]
 [0 0 1 2 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 2 0]
 [0 1 2 0 0 0 1 2 0 2]
 [0 0 0 0 1 2 0 0 0 1]
 [0 0 0 0 0 0 0 1 1 1]
 [2 0 0 0 1 2 2 2 0 1]
 [2 0 1 1 1 2 0 0 0 1]]


In [70]:
final_cycle = (1_000_000_000 - 10) % 7
final_cycle

3

In [71]:
positions_visited.values()

dict_values([(1, 87), (2, 69), (3, 69), (4, 69), (5, 65), (6, 64), (7, 65), (8, 63), (9, 68)])

## SECOND PART

In [72]:
# READ FILE
inputfilepath = './input.txt'

input = []
with open(inputfilepath,'r') as f:
    for line in f:
        input.append(line.rstrip())

In [73]:
mapping = {'O':1, '.':0, '#':2}
panel = []
for line in input:
    row = [mapping[x] for x in line]
    panel.append(row)
np_panel = np.array(panel)
print(np_panel.shape)
np_panel

(100, 100)


array([[1, 0, 0, ..., 0, 0, 1],
       [0, 1, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 2],
       [0, 0, 0, ..., 2, 2, 2],
       [1, 0, 0, ..., 1, 0, 0]])

In [74]:
np_panel_copy = np_panel.copy()
positions_visited = {}

for i in range(1,1_000_00):

    np_panel_copy = cycle(np_panel_copy)

    rock_idx = np.where(np_panel_copy == 1)
    rock_idx_tuple = tuple(zip(rock_idx[0], rock_idx[1]))

    if rock_idx_tuple in positions_visited.keys():        
        cycle_lenght = i - positions_visited[rock_idx_tuple][0]
        print(f'Found cycle at iteration {i} of lenght {cycle_lenght}')
        break
    else:
        positions_visited[rock_idx_tuple] = (i, compute_weight(np_panel_copy))

    if i % 1000 == 0:
        print(f'Completed {i} cycles')

print(compute_weight(np_panel_copy))
print(np_panel_copy)

Found cycle at iteration 178 of lenght 84
101369
[[0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 2]
 [0 0 0 ... 2 2 2]
 [0 0 0 ... 0 0 1]]


In [75]:
final_cycle = (1_000_000_000 - 178) % 84
final_cycle

66

In [79]:
wanted_position = 178 - 84 + 66
wanted_position

160

In [80]:
for position in positions_visited.values():
    if position[0] == wanted_position:
        print(position)

(160, 101292)
