In [1]:
import pandas as pd
import numpy as np
import os, sys
import math
import copy

## PROCESS FIRST SAMPLE

In [4]:
input = ["...#......",
".......#..",
"#.........",
"..........",
"......#...",
".#........",
".........#",
"..........",
".......#..",
"#...#....."]

In [29]:
array_input = []
for line in input:
    list_line = []
    for linechar in line:
        if linechar == '.':
            list_line.append(0)
        elif linechar == '#':
            list_line.append(1)
        else:
            print(f'Unknown char {linechar}')
    array_input.append(list_line)
np_input = np.array(array_input)
np_input.shape
np_input


array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [58]:
def expand_array(array, num_rows, num_cols):
    expanded_array = array.copy()
    new_row = np.zeros((num_cols,))
    for i in range(num_rows-1,0,-1):
        if np.sum(expanded_array[i,:])==0:
            expanded_array = np.insert(expanded_array,i,new_row,axis=0)
            num_rows += 1
    new_col = np.zeros((num_rows,))
    for i in range(num_cols-1,0,-1):
        if np.sum(expanded_array[:,i])==0:
            expanded_array = np.insert(expanded_array,i,new_col,axis=1)
            
    return expanded_array

In [59]:
expanded_array = expand_array(np_input,np_input.shape[0],np_input.shape[1])
print(expanded_array.shape)
expanded_array

(12, 13)


array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [60]:
def get_list_galaxies(map, num_rows, num_cols):
    galaxy_list = []
    for i in range(num_rows):
        for j in range(num_cols):
            if map[i,j] == 1:
                galaxy_list.append((i,j))
    return galaxy_list

In [63]:
galaxy_list = get_list_galaxies(expanded_array,expanded_array.shape[0], expanded_array.shape[1])

In [64]:
def get_galaxy_distances(galaxy_list):
    tot_distance = 0
    for i in range(len(galaxy_list)):
        orig_galaxy = galaxy_list[i]
        for j in range(i + 1, len(galaxy_list)):
            dest_galaxy = galaxy_list[j]
            distance = abs(dest_galaxy[0] - orig_galaxy[0]) + abs(dest_galaxy[1] - orig_galaxy[1])
            tot_distance += distance
    return tot_distance

In [65]:
get_galaxy_distances(galaxy_list)

374

## PROCESS PART 1

In [66]:
# READ FILE
inputfilepath = './input.txt'

input = []
with open(inputfilepath,'r') as f:
    for line in f:
        input.append(line.rstrip())

In [68]:
array_input = []
for line in input:
    list_line = []
    for linechar in line:
        if linechar == '.':
            list_line.append(0)
        elif linechar == '#':
            list_line.append(1)
        else:
            print(f'Unknown char {linechar}')
    array_input.append(list_line)
np_input = np.array(array_input)
print(np_input.shape)
np_input


(140, 140)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [69]:
expanded_array = expand_array(np_input,np_input.shape[0],np_input.shape[1])
print(expanded_array.shape)
expanded_array

(147, 145)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [70]:
galaxy_list = get_list_galaxies(expanded_array,expanded_array.shape[0], expanded_array.shape[1])

In [71]:
get_galaxy_distances(galaxy_list)

9274989

## PROCESS SECOND SAMPLE

In [72]:
input = ["...#......",
".......#..",
"#.........",
"..........",
"......#...",
".#........",
".........#",
"..........",
".......#..",
"#...#....."]

In [73]:
array_input = []
for line in input:
    list_line = []
    for linechar in line:
        if linechar == '.':
            list_line.append(0)
        elif linechar == '#':
            list_line.append(1)
        else:
            print(f'Unknown char {linechar}')
    array_input.append(list_line)
np_input = np.array(array_input)
np_input.shape
np_input


array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

In [74]:
def find_empty_rows(array, rows):
    empty_rows = []
    for i in range(rows):
        if np.sum(array[i,:]) == 0:
            empty_rows.append(i)
    return empty_rows

def find_empty_cols(array, cols):
    empty_cols = []
    for i in range(cols):
        if np.sum(array[:,i]) == 0:
            empty_cols.append(i)
    return empty_cols

In [76]:
empty_rows = np.array(find_empty_rows(np_input,np_input.shape[0]))
empty_cols = np.array(find_empty_cols(np_input,np_input.shape[1]))
empty_rows, empty_cols

(array([3, 7]), array([2, 5, 8]))

In [88]:
def get_older_galaxy_distances(galaxy_list,empty_rows,empty_cols,weight):
    tot_distance = 0
    for i in range(len(galaxy_list)):
        orig_galaxy = galaxy_list[i]
        for j in range(i + 1, len(galaxy_list)):
            dest_galaxy = galaxy_list[j]
            distance = abs(dest_galaxy[0] - orig_galaxy[0]) + abs(dest_galaxy[1] - orig_galaxy[1])
            crossed_empty_rows = np.sum((empty_rows > min(orig_galaxy[0],dest_galaxy[0]))&(empty_rows < max(orig_galaxy[0],dest_galaxy[0])))
            crossed_empty_cols = np.sum((empty_cols > min(orig_galaxy[1],dest_galaxy[1]))&(empty_cols < max(orig_galaxy[1],dest_galaxy[1])))

            tot_distance += distance + (weight-1)*crossed_empty_rows + (weight-1)*crossed_empty_cols
    return tot_distance

In [89]:
galaxy_list = get_list_galaxies(np_input,np_input.shape[0], np_input.shape[1])
galaxy_list

[(0, 3), (1, 7), (2, 0), (4, 6), (5, 1), (6, 9), (8, 7), (9, 0), (9, 4)]

In [91]:
get_older_galaxy_distances(galaxy_list,empty_rows,empty_cols,100)

8410

## PROCESS PART 2

In [92]:
# READ FILE
inputfilepath = './input.txt'

input = []
with open(inputfilepath,'r') as f:
    for line in f:
        input.append(line.rstrip())

In [93]:
array_input = []
for line in input:
    list_line = []
    for linechar in line:
        if linechar == '.':
            list_line.append(0)
        elif linechar == '#':
            list_line.append(1)
        else:
            print(f'Unknown char {linechar}')
    array_input.append(list_line)
np_input = np.array(array_input)
np_input.shape
np_input


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [94]:
empty_rows = np.array(find_empty_rows(np_input,np_input.shape[0]))
empty_cols = np.array(find_empty_cols(np_input,np_input.shape[1]))
empty_rows, empty_cols

(array([  1,   5,  10,  56,  64,  65, 111]), array([ 3, 11, 59, 78, 84]))

In [95]:
galaxy_list = get_list_galaxies(np_input,np_input.shape[0], np_input.shape[1])
galaxy_list

[(0, 25),
 (0, 51),
 (0, 73),
 (0, 82),
 (0, 101),
 (0, 114),
 (0, 130),
 (2, 35),
 (2, 58),
 (3, 92),
 (3, 119),
 (3, 125),
 (4, 2),
 (4, 31),
 (4, 46),
 (4, 66),
 (4, 107),
 (4, 137),
 (6, 16),
 (6, 22),
 (6, 37),
 (6, 77),
 (6, 95),
 (6, 101),
 (7, 8),
 (7, 54),
 (7, 121),
 (8, 42),
 (8, 61),
 (8, 72),
 (8, 88),
 (8, 130),
 (9, 0),
 (9, 81),
 (9, 111),
 (9, 138),
 (11, 12),
 (12, 23),
 (12, 29),
 (12, 47),
 (12, 74),
 (12, 132),
 (13, 97),
 (14, 35),
 (14, 52),
 (14, 87),
 (14, 117),
 (15, 4),
 (15, 58),
 (15, 107),
 (15, 124),
 (15, 137),
 (16, 10),
 (16, 81),
 (16, 94),
 (17, 101),
 (17, 114),
 (17, 129),
 (18, 24),
 (18, 66),
 (18, 72),
 (18, 120),
 (19, 2),
 (19, 31),
 (20, 14),
 (20, 40),
 (20, 60),
 (20, 98),
 (20, 105),
 (21, 76),
 (21, 83),
 (22, 123),
 (23, 19),
 (23, 101),
 (23, 116),
 (23, 129),
 (24, 26),
 (24, 50),
 (24, 91),
 (24, 137),
 (25, 67),
 (26, 0),
 (26, 16),
 (26, 38),
 (26, 44),
 (26, 82),
 (27, 33),
 (27, 75),
 (27, 103),
 (28, 6),
 (28, 96),
 (28, 108),
 (

In [96]:
get_older_galaxy_distances(galaxy_list,empty_rows,empty_cols,1_000_000)

357134560737